name: media_kit_libs_android_video
description: Android package providing video (& audio) native libraries for package:media_kit.
version: 1.3.8
publish_to: none
homepage: https://github.com/media-kit/media-kit.git
repository: https://github.com/media-kit/media-kit.git

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: ">=3.38.6"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmercerind.media_kit_libs_android_video
        pluginClass: MediaKitLibsAndroidVideoPlugin
